####################
# General Config 
####################

set -g default-terminal "tmux-256color"
set -as terminal-features 'tmux-256color:RGB'

####################
# Plugins
####################
TMUX_COLORTAG_USE_POWERLINE=yes
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jaclu/tmux-menus' 
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'MunifTanjim/tmux-suspend'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'
set -g @plugin 'schasse/tmux-jump'

set-option -g @plugin 'b0o/tmux-autoreload'

# has to be last plugin to load
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
####################
# General Settings
####################
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'iterm'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes 'ssh'
set -g aggressive-resize on
set -g allow-rename off
set -g base-index 1
set -g mouse on
set -g visual-activity off
set -g window-status-activity-style 'fg=yellow,bold'

set-option -g default-command "/bin/bash -c 'which reattach-to-user-namespace >/dev/null && exec reattach-to-user-namespace $SHELL -l || exec $SHELL -l'"

setw -g mode-keys vi
setw -g monitor-activity off

####################
# Theme Settings
####################
set -g @plugin 'fabioluciano/tmux-powerkit'

set -g @powerkit_plugins "hostname"
set -g @powerkit_theme "tokyo-night"
set -g @powerkit_theme_variant "night"
set -g @powerkit_status_position "bottom"


####################
# Keyboard Shortcuts
####################
bind-key -n S-Enter send-keys Escape "[13;2u"
set -s extended-keys on
set -as terminal-features 'tmux-256color:extkeys'

bind J resize-pane -D 10
bind K resize-pane -U 10
bind H resize-pane -L 10
bind L resize-pane -R 10

bind X killw
bind x killp

# Floating window popups
bind g display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "lazygit"
bind R display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "ranger"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
